name: .NET Core
on:
  push:
    paths:
      - 'ManifestUpdater/Resources/internal_manifest.json'
  #every 2 hours, 37 minutes past due to congestion and stuff
  schedule:
  - cron: "37 */2 * * *"
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEXUS_APITOKEN: ${{ secrets.NEXUS_APITOKEN }}
jobs:

  build:
    runs-on: windows-latest
    steps:

    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Run Updater
      run: dotnet run --project ./ManifestUpdater 
