name: .NET Core
on:
  push:
    paths:
      - 'ManifestUpdater/Resources/internal_manifest.json'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '5.x'
    - name: Install dependencies 1
      run: dotnet add package Newtonsoft.Json
    - name: Install dependencies 2
      run: dotnet add package NexusModsNET
    - name: Install dependencies 3
      run: dotnet add package Octokit
    - name: Test code 
      run: dotnet test "./ManifestUpdater/ManifestUpdater.csproj"
