name: .NET Core
on:
  push:
    paths:
      - 'ManifestUpdater/Resources/internal_manifest.json'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '5.x'
    - name: Install dependencies 1
      run: dotnet add package Newtonsoft.Json
    - name: Install dependencies 2
      run: dotnet add package NexusModsNET
    - name: Install dependencies 3
      run: dotnet add package Octokit
    - name: .Net Build
  # You may pin to the exact commit or the version.
  # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
      uses: EasyDesk/action-dotnet-build@v1.0.0
      with:
        path: "./ManifestUpdater/ManifestUpdater.csproj" # optional, default is .
    - name: Test code 
      run: dotnet test "./ManifestUpdater"
